<Project>
  <PropertyGroup>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <Deterministic>true</Deterministic>
    <Version>0.3.0</Version>
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
    <PathMap>$(MSBuildThisFileDirectory)=/_/</PathMap>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
</Project>
